#!/bin/bash

docker rm -f neo4j-server
docker run -d -p 7473:7473 -p 7474:7474 -p 7687:7687 --name neo4j-server neo4j-server
#gcloud compute instances --project psjh-238522 delete-access-config balter-neo4j-docker --zone=us-east1-b --access-config-name="external nat"
